from dataclasses import dataclass
from datetime import datetime
from uuid import UUID


@dataclass(slots=True, frozen=True)
class Event:
    """
    Base class for events generated by the World Model.

    Events represent immutable facts about changes observed in the world state.
    They are produced by the World Model and can be consumed by other
    subsystems, such as Memory, for long-term storage or reasoning.

    Attributes:
        object_id: Identifier of the WorldObject associated with this event.
        timestamp: Time when the event occurred.
    """

    object_id: UUID
    timestamp: datetime