"""initial database schema

Revision ID: d2867cabf95f
Revises: 
Create Date: 2026-08-13 23:24:28.343517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2867cabf95f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('world_object_uuid', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('appearance_embedding', sa.BLOB(), nullable=False),
    sa.Column('semantic_location', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.Text(), nullable=False),
    sa.Column('last_seen', sa.Text(), nullable=False),
    sa.Column('confidence', sa.REAL(), nullable=False),
    sa.Column('is_visible', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('world_object_uuid')
    )
    op.create_table('sensor',
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('sensor_uuid', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sensor_id'),
    sa.UniqueConstraint('sensor_uuid')
    )
    op.create_table('world_state_snapshot',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('world_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('observation',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.sensor_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['object.object_id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observation.observation_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('observation')
    op.drop_table('world_state_snapshot')
    op.drop_table('sensor')
    op.drop_table('object')
    # ### end Alembic commands ###
