from uuid import uuid4
from pathlib import Path
import numpy as np
import torch

from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection

from src.perception.detectors.detector import Detector
from src.perception.models.observation import Observation
from src.perception.models.detection import Detection, BoundingBox
from configs.perception.open_vocabulary_detector_config import OpenVocabularyDetectorConfig


class OpenVocabularyDetector(Detector):
    """
    Open-vocabulary implementation of the detector interface.

    Uses a text-conditioned detection model to detect objects based on
    provided prompts rather than a fixed set of trained classes.

    This allows the detector to identify arbitrary objects without
    modifying the model architecture.
    """

    def __init__(
        self, 
        config: OpenVocabularyDetectorConfig
    ):
        """
        Initialize the open-vocabulary detector.

        Loads the processor and model required for text-guided object
        detection.

        Args:
            config: Configuration containing the model path, detection
                prompts, and confidence threshold.
        
        Raises:
            FileNotFoundError: If the configured model does not exist.
        """
        self.config = config

        model_path = Path(config.model_path)
        
        if not model_path.is_dir():
            raise FileNotFoundError(
                f"Open vocabulary model not found:\n{model_path}\n"
                "Run the model setup script or follow the model installation instructions in the README."
            )

        self.processor = AutoProcessor.from_pretrained(
            model_path,
            local_files_only=True
        )

        self.model = AutoModelForZeroShotObjectDetection.from_pretrained(
            model_path,
            local_files_only=True
        )

    def detect(self, observation: Observation) -> list[Detection]:
        """
        Detect objects in an observation.

        Runs inference on the observation image, converts the raw model
        outputs into bounding boxes, and returns standardized Detection
        objects used by the perception pipeline.

        Args:
            observation: Observation containing the image data.

        Returns:
            List of detections generated by the open-vocabulary model.
        """
        outputs, inputs = self._predict(observation.payload)

        results = self._post_process(
            outputs,
            inputs,
            observation.payload.shape[:2]
        )

        return self._results_to_detections(results)

    def _predict(self, image: np.ndarray):
        """
        Run inference using the open-vocabulary model.

        Prepares the image and text prompts using the processor, executes
        the model, and returns the raw outputs together with the processed
        inputs required for post-processing.

        Args:
            image: RGB image represented as a NumPy array.

        Returns:
            Tuple containing raw model outputs and processor inputs.
        """
        inputs = self.processor(
            images=image,
            text=self.config.prompts,
            return_tensors="pt"
        )

        with torch.no_grad():
            outputs = self.model(**inputs)

        return outputs, inputs

    def _post_process(
        self, 
        outputs, 
        inputs, 
        image_size
    ):
        """
        Convert raw model outputs into detected objects.

        Applies the model-specific post-processing step to convert raw
        predictions into bounding boxes, labels, and confidence scores.

        Args:
            outputs: Raw outputs generated by the detection model.
            inputs: Processor outputs containing information required by
                the post-processing method.
            image_size: Original image dimensions as (height, width).

        Returns:
            Processed detection results containing labels, scores, and
            bounding boxes.
        """
        height, width = image_size

        results = self.processor.post_process_grounded_object_detection(
            outputs,
            inputs.input_ids,
            threshold=self.config.confidence_threshold,
            target_sizes=[(height, width)]
        )

        return results[0]

    def _results_to_detections(self, results) -> list[Detection]:
        """
        Convert model results into application detection models.

        Transforms the model-specific output format into the standardized
        Detection domain model used throughout the perception subsystem.

        Args:
            results: Processed model output containing detected labels,
                confidence scores, and bounding boxes.

        Returns:
            List of Detection objects.
        """
        detections = []

        for score, label, box in zip(
            results["scores"],
            results["labels"],
            results["boxes"]
        ):
            x1, y1, x2, y2 = box.tolist()

            detection = Detection(
                id=str(uuid4()),
                entity=label.lower().removeprefix("a "),
                confidence=float(score),
                bounding_box=BoundingBox(
                    x1=float(x1),
                    y1=float(y1),
                    x2=float(x2),
                    y2=float(y2),
                ),
            )

            detections.append(detection)

        return detections