from uuid import uuid4
import numpy as np

from rfdetr import RFDETRSmall

from src.perception.detectors.detector import Detector
from src.perception.models.observation import Observation
from src.perception.models.detection import Detection, BoundingBox
from configs.perception.rf_detr_detector_config import RFDETRDetectorConfig


class RFDETRDetector(Detector):
    """RF-DETR-based implementation of the detector interface."""

    def __init__(self, config: RFDETRDetectorConfig):
        """Initialize the RF-DETR detector.

        Args:
            config: Configuration containing model path and detection settings.
        """
        self.config = config

        self.model = RFDETRSmall(
            pretrain_weights=config.model_path
        )

    def detect(self, observation: Observation) -> list[Detection]:
        """Detect objects in an observation.

        Args:
            observation: Observation containing image data.

        Returns:
            List of detections generated by the RF-DETR model.
        """
        results = self._predict(observation.payload)

        return self._results_to_detections(results)

    def _predict(self, image: np.ndarray):
        """Run inference using the RF-DETR model.

        Args:
            image: RGB image represented as a NumPy array.

        Returns:
            Raw RF-DETR inference results.
        """
        return self.model.predict(
            image,
            threshold=self.config.confidence_threshold
        )

    def _results_to_detections(self, results) -> list[Detection]:
        """Convert RF-DETR results into application detection models.

        Args:
            results: Raw detections returned by RF-DETR.

        Returns:
            List of standardized detections.
        """
        detections = []

        for xyxy, _, confidence, _, _, data in results:

            x1, y1, x2, y2 = xyxy

            detection = Detection(
                id=str(uuid4()),
                entity=data["class_name"],
                confidence=float(confidence),
                bounding_box=BoundingBox(
                    x1=float(x1),
                    y1=float(y1),
                    x2=float(x2),
                    y2=float(y2),
                ),
            )

            detections.append(detection)

        return detections