from ultralytics import YOLO
from uuid import uuid4
import numpy as np

from perception.detectors.detector import Detector
from perception.models.observation import Observation
from perception.models.detection import Detection, BoundingBox
from configs.perception.yolo_detector_config import YOLODetectorConfig


class YOLODetector(Detector):
    """YOLO-based implementation of the detector interface."""

    def __init__(self, config: YOLODetectorConfig):
        """Initialize the YOLO detector.

        Args:
            config: Configuration containing model path and detection settings.
        """
        self.config = config
        self.model = YOLO(config.model_path)

    def detect(self, observation: Observation) -> list[Detection]:
        """Detect objects in an observation.

        Args:
            observation: Observation containing image data.

        Returns:
            List of detections generated by the YOLO model.
        """
        results = self._predict(observation.payload)

        return self._results_to_detections(results)

    def _predict(self, image: np.ndarray):
        """Run inference using the YOLO model.

        Args:
            image: RGB image represented as a NumPy array.

        Returns:
            Raw YOLO inference results.
        """
        return self.model(image, conf=self.config.confidence_threshold)

    def _results_to_detections(self, results) -> list[Detection]:
        """Convert YOLO results into application detection models.

        Args:
            results: Raw results returned by the YOLO model.

        Returns:
            List of standardized detections.
        """
        detections = []

        for result in results:
            for box in result.boxes:

                class_id = int(box.cls.item())
                confidence = float(box.conf.item())

                x1, y1, x2, y2 = box.xyxy[0]

                detection = Detection(
                    id=str(uuid4()),
                    entity=result.names[class_id],
                    confidence=confidence,
                    bounding_box=BoundingBox(
                        x1=float(x1),
                        y1=float(y1),
                        x2=float(x2),
                        y2=float(y2),
                    ),
                )

                detections.append(detection)

        return detections