from uuid import UUID
from datetime import datetime

from src.world.events.object_moved_event import ObjectMovedEvent
from src.world.events.object_appeared_event import ObjectAppearedEvent
from src.world.events.object_disappeared_event import ObjectDisappearedEvent
from src.world.events.object_reappeared_event import ObjectReappearedEvent

class EventGenerator:
    """
    Generates immutable event objects from World Model state changes.

    The EventGenerator is responsible only for constructing event instances.
    It does not determine when an event should occur and does not store
    generated events. The World Model is responsible for detecting state
    changes and requesting the appropriate event creation.

    Events generated by this class can be passed to other subsystems, such as
    Memory, for storage or later reasoning.
    """

    def generate_object_moved(
        self,
        object_id: UUID,
        timestamp: datetime,
        from_location: UUID | None,
        to_location: UUID | None
    ) -> ObjectMovedEvent:
        """
        Creates an event representing an object's location change.

        Args:
            object_id: Identifier of the object that moved.
            timestamp: Time when the movement occurred.
            from_location: Previous known location of the object.
            to_location: New known location of the object.

        Returns:
            An ObjectMovedEvent describing the movement.
        """
        return ObjectMovedEvent(
            object_id=object_id,
            timestamp=timestamp,
            from_location=from_location,
            to_location=to_location
        )

    def generate_object_appeared(
        self,
        object_id: UUID,
        timestamp: datetime, 
        location: UUID | None
    ) -> ObjectAppearedEvent:
        """
        Creates an event representing a newly observed object.

        Args:
            object_id: Identifier of the object that appeared.
            timestamp: Time when the object was first observed.
            location: Location where the object was observed, if available.

        Returns:
            An ObjectAppearedEvent describing the appearance.
        """
        return ObjectAppearedEvent(
            object_id=object_id,
            timestamp=timestamp,
            location=location
        )

    def generate_object_disappeared(
        self, 
        object_id: UUID,
        timestamp: datetime,
        last_known_location: UUID | None
    ) -> ObjectDisappearedEvent:
        """
        Creates an event representing an object no longer being observed.

        Args:
            object_id: Identifier of the object that disappeared.
            timestamp: Time when the disappearance was detected.
            last_known_location: Last known location of the object, if available.

        Returns:
            An ObjectDisappearedEvent describing the disappearance.
        """
        return ObjectDisappearedEvent(
            object_id=object_id,
            timestamp=timestamp,
            last_known_location=last_known_location
        )

    def generate_object_reappeared(
        self,
        object_id: UUID,
        timestamp: datetime,
        location: UUID | None
    ) -> ObjectReappearedEvent:
        """
        Creates an event representing an object becoming visible again after
        previously being marked as disappeared.

        Args:
            object_id: Identifier of the object that reappeared.
            timestamp: Time when the reappearance was detected.
            location: Location where the object was observed again, if available.

        Returns:
            An ObjectReappearedEvent describing the reappearance.
        """
        return ObjectReappearedEvent(
            object_id=object_id,
            timestamp=timestamp,
            location=location
        )