from datetime import datetime
from uuid import UUID

import numpy as np

from src.database.database import SessionLocal
from src.database.models.world_state_snapshot import WorldStateModel
from src.database.models.sensor import SensorModel
from src.database.models.observation import ObservationModel
from src.database.models.object import ObjectModel
from src.database.models.event import EventModel

from src.perception.models.observation import Observation
from src.world.models.world_object import WorldObject
from src.world.events.event import Event
from src.world.events.object_appeared_event import ObjectAppearedEvent
from src.world.events.object_disappeared_event import ObjectDisappearedEvent
from src.world.events.object_moved_event import ObjectMovedEvent
from src.world.events.object_reappeared_event import ObjectReappearedEvent

class Memory:
    """
    Provides persistence operations for the Space Observer application.

    The Memory subsystem acts as the interface between the application and
    the database. It is responsible for storing and loading application data
    but does not decide when persistence operations should occur.

    Persistence decisions are made by the application orchestration layer,
    while Memory handles the corresponding database operations.
    """

    def store_sensor(self, sensor_config):
        """
        Stores a sensor if it does not already exist.

        Sensors are identified by their sensor UUID. If a sensor with the
        same UUID already exists, no database operation is performed.

        Args:
            sensor_config: Configuration containing the sensor UUID and name.
        """
        with SessionLocal() as session:
            existing_sensor = (
                session.query(SensorModel)
                .filter_by(sensor_uuid=sensor_config.sensor_id)
                .first()
            )

            if existing_sensor is not None:
                return

            sensor_model = SensorModel(
                sensor_uuid=sensor_config.sensor_id,
                name=sensor_config.name
            )

            session.add(sensor_model)
            session.commit()


    def store_observation(self, observation: Observation, path: str) -> int:
        """
        Stores an observation and returns its database identifier.

        The observation must reference a sensor that has already been stored
        in the database.

        Args:
            observation: Observation produced by a sensor.
            path: Filesystem path where the observation data is stored.

        Returns:
            The database-generated observation ID.

        Raises:
            ValueError: If the observation references an unknown sensor.
        """
        with SessionLocal() as session:
            observation_sensor = (
                session.query(SensorModel)
                .filter_by(sensor_uuid=observation.sensor_id)
                .first()
            )

            if observation_sensor is None:
                raise ValueError(
                    f"Sensor '{observation.sensor_id}' does not exist."
                )

            obs = ObservationModel(
                timestamp=observation.timestamp.isoformat(),
                path=path,
                sensor_id=observation_sensor.sensor_id
            )

            session.add(obs)
            session.flush()

            observation_id = obs.observation_id

            session.commit()

            return observation_id


    def store_event(self, event: Event, observation_id: int):
        """
        Stores an event associated with an observation and object.

        The event type is derived from the event class name, while
        event-specific information is stored using the event's payload.

        Args:
            event: Event generated by the World Model.
            observation_id: Database ID of the observation that caused
                the event.

        Raises:
            ValueError: If the event references an object that has not been
                stored in the database.
        """
        with SessionLocal() as session:

            object_data = (
                session.query(ObjectModel)
                .filter_by(world_object_uuid=str(event.object_id))
                .first()
            )

            if object_data is None:
                raise ValueError(
                    f"Object '{event.object_id}' does not exist."
                )

            event_data = EventModel(
                type=type(event).__name__.removesuffix("Event").lower(),
                timestamp=event.timestamp.isoformat(),
                data=event.payload,
                observation_id=observation_id,
                object_id=object_data.object_id,
            )

            session.add(event_data)
            session.commit()


    def store_object(self, world_object: WorldObject):
        """
        Stores or updates a WorldObject in the database.

        If the WorldObject does not already exist, a new database record is
        created. Otherwise, the existing record is updated to reflect the
        current state of the WorldObject.

        Appearance embeddings are serialized to binary data before storage.

        Args:
            world_object: WorldObject whose current state should be persisted.
        """
        with SessionLocal() as session:
            object_model = (
                session.query(ObjectModel)
                .filter_by(
                    world_object_uuid=str(world_object.id)
                )
                .first()
            )

            if object_model is None:
                object_model = ObjectModel(
                    world_object_uuid=str(world_object.id),
                    label=world_object.label,
                    appearance_embedding=world_object.appearance_embedding.tobytes(),
                    semantic_location=(
                        str(world_object.semantic_location)
                        if world_object.semantic_location is not None
                        else None
                    ),
                    first_seen=world_object.first_seen.isoformat(),
                    last_seen=world_object.last_seen.isoformat(),
                    confidence=world_object.confidence,
                    is_visible=int(world_object.is_visible),
                )

                session.add(object_model)

            else:
                object_model.label = world_object.label
                object_model.appearance_embedding = (
                    world_object.appearance_embedding.tobytes()
                )
                object_model.semantic_location = (
                    str(world_object.semantic_location)
                    if world_object.semantic_location is not None
                    else None
                )
                object_model.first_seen = world_object.first_seen.isoformat()
                object_model.last_seen = world_object.last_seen.isoformat()
                object_model.confidence = world_object.confidence
                object_model.is_visible = int(world_object.is_visible)

            session.commit()


    def store_world_state(self, world_objects: dict[UUID, WorldObject]):
        """
        Stores a snapshot of the current World Model state.

        WorldObjects are serialized into JSON-compatible data before being
        stored as a world-state snapshot. Appearance embeddings are converted
        to lists because JSON cannot directly represent NumPy arrays.

        Args:
            world_objects: Mapping of WorldObject UUIDs to their current
                WorldObject instances.
        """
        data = {
            str(object_id): {
                "id": str(world_object.id),
                "label": world_object.label,
                "appearance_embedding": (
                    world_object.appearance_embedding.tolist()
                ),
                "semantic_location": (
                    str(world_object.semantic_location)
                    if world_object.semantic_location is not None
                    else None
                ),
                "first_seen": world_object.first_seen.isoformat(),
                "last_seen": world_object.last_seen.isoformat(),
                "confidence": world_object.confidence,
                "is_visible": world_object.is_visible,
            }
            for object_id, world_object in world_objects.items()
        }

        state = WorldStateModel(
            timestamp=datetime.now().isoformat(),
            world_data=data
        )

        with SessionLocal() as session:
            session.add(state)
            session.commit()


    def load_last_state(self) -> dict[UUID, WorldObject] | None:
        """
        Loads the most recent World Model state snapshot.

        The stored JSON-compatible representation is deserialized back into
        WorldObject instances, including reconstruction of UUIDs, timestamps,
        semantic locations, NumPy embeddings, and visibility state.

        Returns:
            A mapping of WorldObject UUIDs to WorldObject instances, or None
            if no world-state snapshot exists in the database.
        """
        with SessionLocal() as session:
            state = (
                session.query(WorldStateModel)
                .order_by(WorldStateModel.state_id.desc())
                .first()
            )

        if state is None:
            return None

        world_objects = {}

        for object_id, data in state.world_data.items():
            world_object = WorldObject(
                id=UUID(data["id"]),
                label=data["label"],
                appearance_embedding=np.array(
                    data["appearance_embedding"],
                    dtype=np.float32
                ),
                semantic_location=(
                    UUID(data["semantic_location"])
                    if data["semantic_location"] is not None
                    else None
                ),
                first_seen=datetime.fromisoformat(data["first_seen"]),
                last_seen=datetime.fromisoformat(data["last_seen"]),
                confidence=data["confidence"],
                is_visible=bool(data["is_visible"]),
            )

            world_objects[UUID(object_id)] = world_object

        return world_objects